Review
akalji-epam-rd/epm-java-lab-jul-2019 pull request #16
Opened 2019-07-19 09:37 UTC by lostforstupid

2019-07-19 10:04 UTC, lostforstupid commented on src/main/java/com/epam/lab/library/dao/AuthorDaoImpl.java
> +                return id;
What's the point of several return statements?
You can initialize id with null before you try to get it from resultSet. It will be more clear what you are trying to return from this method.

2019-07-19 10:04 UTC, lostforstupid commented on src/main/java/com/epam/lab/library/dao/AuthorDaoImpl.java
> +                resultSet.close();
This line is executed anyway, why not write it outside if and else blocks once?

2019-07-19 10:44 UTC, lostforstupid commented on src/main/java/com/epam/lab/library/AuthFilter.java
> +    private boolean userIsExist(String email, String password, HttpSession session, UserDao userDao) {
boolean methods and variables names should start with "is"

2019-07-19 10:47 UTC, lostforstupid commented on src/main/java/com/epam/lab/library/controller/BookController.java
> +        switch (type) {
Why do you need switch here if you only check one value?...

2019-07-19 10:51 UTC, akalji commented on src/main/java/com/epam/lab/library/dao/AuthorDaoImpl.java
> +                resultSet.close();
Also think about try-with-resources. It is good practice

2019-07-19 10:53 UTC, akalji commented on src/main/java/com/epam/lab/library/Application.java
> +public class Application {
Unnecessary class

2019-07-19 10:53 UTC, lostforstupid commented on src/main/java/com/epam/lab/library/controller/ItemAjaxController.java
> +        if (pathInfo[1].equals("get")) {
When you compare something with a constant, you should always put constant first to avoid NPE for sure

2019-07-19 10:54 UTC, akalji commented on src/main/java/com/epam/lab/library/AuthFilter.java
> +    public void destroy() {
Why do you override destroy method without calling super?

2019-07-19 10:55 UTC, akalji commented on src/main/java/com/epam/lab/library/controller/ItemAjaxController.java
> +                e.printStackTrace();
You should log errors

2019-07-19 10:55 UTC, akalji commented on src/main/java/com/epam/lab/library/controller/ItemAjaxController.java
> +            e.printStackTrace();
You should log errors

2019-07-19 10:56 UTC, akalji commented on src/main/java/com/epam/lab/library/controller/ItemAjaxController.java
> +        System.out.println("doDeleteMethod");
DO NOT USE SOUT! ONLY LOG!!!!!!!!

2019-07-19 10:57 UTC, akalji commented on src/main/java/com/epam/lab/library/controller/ItemController.java
> +            e.printStackTrace();
Log it!

2019-07-19 11:02 UTC, akalji commented on src/main/java/com/epam/lab/library/dao/AuthorDaoImpl.java
> +            String query = "UPDATE library.authors SET name='" + author.getName() + "', lastname='" + author.getLastName() + "' " +
Jesus. Use parametrized queries. Do not use сoncatenation! It is vulnerable for SQL Injection

2019-07-19 11:06 UTC, Astel reviewed
I have a few things to consider: 
- Using Option in cases, when you want to return an object of null
- Using CTRL+ALT+L and CTRL+ALT+O to prevent most of style and unused imports issues
- Javadoc. Don't push before documentation is ready.
- Same for TODO. You need to complete task before push

2019-07-19 11:06 UTC, Astel commented on src/main/java/com/epam/lab/library/controller/ItemController.java
> +import com.epam.lab.library.domain.Role;
Unused.

2019-07-19 11:06 UTC, Astel commented on src/main/java/com/epam/lab/library/dao/AuthorDaoImpl.java
> +    /**
Follow javadoc style pls

2019-07-19 11:06 UTC, Astel commented on src/main/java/com/epam/lab/library/dao/AuthorDaoImpl.java
> +     * Saves given author in database
Empty line between header and list of params

2019-07-19 11:06 UTC, Astel commented on src/main/java/com/epam/lab/library/dao/AuthorDaoImpl.java
> +            String query = "SELECT authors.id as a_id, authors.name as a_name, authors.lastname as a_lastname, books.id as b_id, books.name as b_name, description as b_description " +
It will be good to extract queries as separate string constant or method

2019-07-19 11:06 UTC, Astel commented on src/main/java/com/epam/lab/library/dao/AuthorDaoImpl.java
> +        try {
Use try-with-resources statement like: https://stackoverflow.com/questions/8066501/how-should-i-use-try-with-resources-with-jdbc

2019-07-19 11:06 UTC, Astel commented on src/main/java/com/epam/lab/library/dao/AuthorDaoImpl.java
> +            author.setId(resultSet.getInt("a_id"))
Extract field names as string constants

2019-07-19 11:06 UTC, Astel commented on src/main/java/com/epam/lab/library/dao/AuthorDaoImpl.java
> +        return null;
Return empty list instead of null

2019-07-19 11:06 UTC, Astel commented on src/main/java/com/epam/lab/library/dao/AuthorDaoImpl.java
> +    public Author getById(int id) {
It will be really good to use Option here

2019-07-19 11:06 UTC, Astel commented on src/main/java/com/epam/lab/library/Application.java
> +
Delete extra lines pls. One empty line between block of code is enough

2019-07-19 11:06 UTC, Astel commented on src/main/java/com/epam/lab/library/AuthFilter.java
> +public class AuthFilter implements Filter {
Move into separate package

2019-07-19 11:06 UTC, Astel commented on src/main/java/com/epam/lab/library/LogoutServlet.java
> +public class LogoutServlet extends HttpServlet {
Move into controllers package

2019-07-19 11:06 UTC, Astel commented on src/main/java/com/epam/lab/library/controller/ItemAjaxController.java
> +        System.out.println("doPostMethod");
Replace all System.out.println with Log methods

2019-07-19 11:06 UTC, Astel commented on src/main/java/com/epam/lab/library/controller/ItemAjaxController.java
> +        try {
Try-with-resources

2019-07-19 11:06 UTC, Astel commented on src/main/java/com/epam/lab/library/controller/ItemAjaxController.java
> +            // TODO: change delete signature methods delete to delete(Integer id) instead of delete (Item item)
Why not implemented?

2019-07-19 11:06 UTC, Astel commented on src/main/java/com/epam/lab/library/controller/ItemAjaxController.java
> +
Seems like unnecessary empty lines

2019-07-19 11:06 UTC, Astel commented on src/main/java/com/epam/lab/library/dao/AuthorDaoImpl.java
> +//TODO put ResultSet in try with resources
Good idea. Why not implemented?

2019-07-19 12:33 UTC, akalji requested changes

2019-07-19 12:33 UTC, akalji commented on src/main/java/com/epam/lab/library/dao/AuthorDaoImpl.java
> +        Connection connection = null;
Connection connection;

2019-07-19 12:33 UTC, akalji commented on src/main/java/com/epam/lab/library/dao/AuthorDaoImpl.java
> +                resultSet.close();
try-with-resources

2019-07-19 12:33 UTC, akalji commented on src/main/java/com/epam/lab/library/dao/ItemDaoImpl.java
> +            System.out.println("Update item with id: " + id + " was successful");
Log it =)

2019-07-22 16:54 UTC, akalji approved these changes

2019-07-22 16:55 UTC, merged