feat(cp): add basic connection pool
akalji-epam-rd/epm-java-lab-jul-2019 pull request #3
Opened 2019-07-06 19:33 UTC by RomanAbaev

i create basic caonnection pool
q: i don't really know how can i test this connection pool, would be great if you hint me, thanks

2019-07-07 13:20 UTC, akalji commented on src/main/java/com/epam/lab/library/connectionpool/ConnectionPool.java
> +    private static volatile ConnectionPool instance;
Do not use volatile with Object =)

2019-07-07 13:20 UTC, akalji commented on src/main/java/com/epam/lab/library/connectionpool/ConnectionPool.java
> +    private Vector<Connection> usedConnections;
Using interfaces is recommended. Also Vector class is depricated

2019-07-08 13:22 UTC, dodo0101 approved these changes

2019-07-08 13:23 UTC, Dji-key requested changes
No

2019-07-08 13:23 UTC, dodo0101 requested changes
please change

2019-07-08 13:25 UTC, RomanAbaev commented
> please change

okay, chief!

2019-07-08 13:28 UTC, dodo0101 approved these changes

2019-07-08 13:29 UTC, Dji-key commented on src/main/java/com/epam/lab/library/connectionpool/ConnectionPool.java
> +public class ConnectionPool implements AutoCloseable {
No

2019-07-08 13:30 UTC, Dji-key requested changes
Again

2019-07-08 13:51 UTC, Dji-key commented on src/main/java/com/epam/lab/library/connectionpool/ConnectionPool.java
> +        if (localInstance == null) {
Lazy initialization is deprecated by us

2019-07-08 14:04 UTC, Dji-key approved these changes

2019-07-08 14:04 UTC, Dji-key commented on src/main/java/com/epam/lab/library/connectionpool/ConnectionPool.java
> +    }
Change lazy initialization to eager

2019-07-08 14:04 UTC, Dji-key commented on src/main/java/com/epam/lab/library/connectionpool/ConnectionPool.java
> +            availableConnections = new ArrayList<>();
Change to LinkedList cause remove too slow vs LinkedList.addLast / removeLast

2019-07-08 14:07 UTC, merged